name = "koreader-sync"
main = "src/index.ts"
compatibility_date = "2026-03-25"

[vars]
SESSION_TTL_HOURS = "168"

[[d1_databases]]
binding = "DB"
database_name = "koreader-sync-db"
database_id = "7fa7672a-a900-47b7-8d39-7207e12de4f4"
migrations_dir = "migrations"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
